name: Deploy Static Website to Azure

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Azure CLI
      uses: azure/CLI@v1

    - name: Upload to Azure Blob Storage
      env:
        AZURE_STORAGE_ACCOUNT: ${{ secrets.bhanupractice }}
        AZURE_STORAGE_KEY: ${{ secrets.l+8sVS6IW0HLFmbRKWhjmCqyEviX7JLWo5H4ruNGT10YD5fgnD4eki0rA0TFCwgoeXqEtYRn3V4V+AStenrNUQ== }}
      run: |
        az storage blob upload-batch \
          --account-name $AZURE_STORAGE_ACCOUNT \
          --account-key $AZURE_STORAGE_KEY \
          --source ./ \
          --destination '$web' \
          --overwrite
