name: Deploy Static Website to Azure

on:
  push:
    branches:
      - main  # Triggers the workflow on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Log in to Azure using Static Web Apps API Token
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GRAY_BAY_085A8200F }}

    # Step 3: Enable Static Website Hosting for the Storage Account
    - name: Enable Static Website Hosting
      run: |
        az storage blob service-properties update \
          --account-name bhanupractice \
          --static-website \
          --index-document index.html \
          --error-document error.html

    # Step 4: Upload Website Files to the Blob Storage $web Container
    - name: Deploy Static Files to Azure Blob Storage
      run: |
        az storage blob upload-batch \
          --account-name bhanupractice \
          --source ./dist \  # Path to your static website files (adjust if different)
          --destination '$web' \
          --overwrite
