name: Deploy Static Website to Azure

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Azure CLI
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

    - name: Debug Environment Variables
      run: |
        echo "AZURE_STORAGE_ACCOUNT=$AZURE_STORAGE_ACCOUNT"
      env:
        AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}

    - name: Upload to Azure Blob Storage
      env:
        AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
        AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}
      run: |
        az storage blob upload-batch \
          --account-name bhanupractice
          --account-key $AZURE_STORAGE_KEY \
          --source . \
          --destination '$web' \
          --overwrite
