name: Deploy Static Website to Azure

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Log in to Azure using API Token
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GRAY_BAY_085A8200F }}

    # Step 3: Enable Static Website Hosting
    - name: Enable Static Website Hosting
      run: |
        az storage blob service-properties update \
          --account-name bhanupractice \
          --static-website \
          --index-document index.html \
          --error-document error.html

    # Step 4: Deploy Static Files to Azure Blob Storage
    - name: Upload Static Website Files
      run: |
        az storage blob upload-batch \
          --account-name bhanupractice \
          --source ./dist \  # Replace this with the path to your website files
          --destination '$web' \
          --overwrite
