name: Deploy Static Website to Azure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Azure CLI
      uses: azure/CLI@v2

    - name: Log in to Azure (Interactive)
      run: az login  # This will require you to authenticate manually during the workflow run

    - name: Enable Static Website Hosting
      run: |
        az storage blob service-properties update \
          --account-name bhanupractice \
          --static-website \
          --index-document index.html \
          --error-document error.html

    - name: Deploy Static Files to Azure Blob Storage
      run: |
        az storage blob upload-batch \
          --account-name bhanupractice \
          --source ./dist \
          --destination '$web' \
          --overwrite
