name: Deploy Static Website to Azure

on:
  push:
    branches:
      - main  # Trigger deployment on changes pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Azure CLI
      uses: azure/CLI@v2

    - name: Authenticate with Azure
      run: |
        az login --service-principal \
          --username ${{ secrets.AZURE_CLIENT_ID }} \
          --password ${{ secrets.AZURE_CLIENT_SECRET }} \
          --tenant ${{ secrets.AZURE_TENANT_ID }}

    - name: Enable Static Website Hosting (If Not Already Enabled)
      run: |
        az storage blob service-properties update \
          --account-name bhanupractice \
          --account-key ${{ secrets.AZURE_STORAGE_KEY }} \
          --static-website \
          --index-document index.html \
          --error-document error.html

    - name: Deploy Static Files to Azure Blob Storage
      run: |
        az storage blob upload-batch \
          --account-name bhanupractice \
          --account-key ${{ secrets.AZURE_STORAGE_KEY }} \
          --source ./dist \  # Replace this with the directory containing your website files
          --destination '$web' \
          --overwrite
