name: Deploy Static Website to Azure Blob Storage

on:
  push:
    branches:
      - main  # Trigger deployment on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger deployment on pull requests to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Azure Blob Storage

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Azure CLI
      - name: Set up Azure CLI
        uses: azure/CLI@v2

      # Step 3: Log in to Azure using API Token
      - name: Log in to Azure
        with: 
            creds: ${{ secrets.AZURE_MY_SP }}

      # Step 4: Enable Static Website Hosting for the Blob Storage
      - name: Enable Static Website Hosting
        run: |
          az storage blob service-properties update \
            --account-name bhanupractice \
            --static-website \
            --index-document index.html \
            --error-document error.html

      # Step 5: Upload Static Files to Blob Storage
      - name: Upload Files to Azure Blob Storage
        run: |
          az storage blob upload-batch \
            --account-name bhanupractice \
            --source ./dist \  # Update this to your static files directory
            --destination '$web' \
            --overwrite
